import type { Metadata } from 'next'
// import { getMessages } from 'next-intl/server'
import { Poppins } from 'next/font/google'
import { StoreProvider } from '@/providers/StoreProvider'
import { QueryProvider } from '@/providers/QueryProvider'
import './globals.css'
// import { IntlProvider } from '@/providers/IntlProvider'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const messages = await getMessages()

  return (
    <html>
      <body className={poppins.className}>
        {/* <IntlProvider messages={messages} locale="id">
        </IntlProvider> */}
        <StoreProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  )
}